[package]

name = "i2cdev"
version = "0.4.1"
authors = ["Paul Osborne <osbpau@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-embedded/rust-i2cdev"
homepage = "https://github.com/rust-embedded/rust-i2cdev"
documentation = "http://rust-embedded.github.io/rust-i2cdev"
description = """
Provides API for safe access to Linux i2c device interface.

https://www.kernel.org/doc/Documentation/i2c/dev-interface
"""

[dependencies]
libc = "0.2"
bitflags = "1"
byteorder = "1"
nix = { git = "https://github.com/nix-rust/nix/", rev = "196b05b5c7b" }

[dev-dependencies]
docopt = "0.8"
